### PR TITLE
Indonesian Translation 

### PR DESCRIPTION
**Pull request by XtarsAgency**
This Bundle is not up-to-date yet, but you can still implement it for indonesian players

### CODE REVIEW

**Comment by XtarsAgency** [comment]
And oh no i forgot to add 2, new factories
carbon-compressor
etymology

**Comment by SunkyMP3G** [comment]
Just don't make sprites for this mod, maybe make your own mod and upgrade your spriting skills
My sprites aren't very good too, but I'm still learning

**Comment by SunkyMP3G** [comment]
And file name must be "bundle_id_ID.properties"

**Comment by XtarsAgency** [comment]
> And file name must be "bundle_id_ID.properties"

You can change the name of the file in your computer though

**Comment by XtarsAgency** [comment]
> Just don't make sprites for this mod, >maybe make your own mod<[no i cant, i only understand HJSON at its simplest and im using templates] 

and upgrade your spriting skills >My sprites aren't very good too, but I'm still learning<[You can hire me as a spriter, as long its not those hard detailed sprites like those T6 unit sprites]

**Comment by SunkyMP3G** [comment]
Please update this bundle, I won't merge it outdated

**Pull request closed without merging**
