### PR TITLE
T2 Unit- "Current" Sprite

### PR DESCRIPTION
**Pull request by XtarsAgency**
Added a T2 unit of "Spark" because we now have Spark Constructors (air constructor). But no code, im still doing it

### CODE REVIEW

**Comment by SunkyMP3G** [comment]
I'm not making any T2 at the moment, and the planet's sprites style is dark.

You can make translations or maybe make changes in the code (for bug fixes, for example)

**Comment by XtarsAgency** [comment]
> You can make >translations<
Maybe, indonesian translation works

**Comment by SunkyMP3G** [comment]
For indonesian translations, create a file named "bundle_id_ID.properties", copy everything from "bundle.properties" file, and translate (don't touch comments like "# Items", please)

**Comment by SunkyMP3G** [comment]
And also delete these sprites in repo, please. Or make a new branch for translation

**Comment by XtarsAgency** [comment]
Dont worry, i probably have no idea what is that anyway (#items) because im just a spriter and a translator

**Comment by SunkyMP3G** [comment]
These are just comments for my navigation, they aren't touching code

**Pull request closed without merging**
